export interface UnifiedTask {
  id: string
  planId: string
  title: string
  description: string
  type: "Build" | "Testing" | "Design" | "Requirements" | "Documentation" | "Framework" | "Component"
  category: string
  epic: string
  status: "To Do" | "In Progress" | "Done"
  priority: "Critical" | "High" | "Medium" | "Low"
  storyPoints: number
  estimateDuration: string
  dueDate: string
  completedDate: string | null
  phase: string
  link?: string
  expectedResult?: string
  assignee?: string
  component?: string
}

export const APPLICATION_PAGES = [
  { value: "/", label: "Dashboard" },
  { value: "/analytics", label: "Analytics" },
  { value: "/api-docs", label: "API Documentation" },
  { value: "/auth/login", label: "Login Page" },
  { value: "/bundle-deals", label: "Bundle Deals" },
  { value: "/bundle-deals/new", label: "New Bundle Deal" },
  { value: "/customer-discounts", label: "Customer Discounts" },
  { value: "/customer-discounts/new", label: "New Customer Discount" },
  { value: "/customers/tiers", label: "Customer Tiers" },
  { value: "/customers/tiers/bulk-upload", label: "Bulk Tier Upload" },
  { value: "/inventory-discounts", label: "Inventory Discounts" },
  { value: "/inventory-discounts/new", label: "New Inventory Discount" },
  { value: "/market-pricing", label: "Market Pricing" },
  { value: "/market-pricing/volume", label: "Volume Pricing" },
  { value: "/price-search", label: "Price Search" },
  { value: "/price-tracking", label: "Price Tracking" },
  { value: "/pricing", label: "Pricing" },
  { value: "/promo-codes", label: "Promo Codes" },
  { value: "/product/[id]", label: "Product Detail" },
  { value: "/products", label: "Products" },
  { value: "/profile", label: "Profile" },
  { value: "/promotion-detection", label: "Promotion Detection" },
  { value: "/promotions", label: "Promotions" },
  { value: "/promotions/dashboard", label: "Promotions Dashboard" },
  { value: "/promotions/history", label: "Promotion History" },
  { value: "/promotions/new", label: "New Promotion" },
  { value: "/restoration-tracker", label: "Restoration Tracker" },
  { value: "/settings", label: "Settings" },
  { value: "/simulator", label: "Pricing Simulator" },
  { value: "/task-planning", label: "Task Planning" },
  { value: "/task-planning/user-stories", label: "User Stories" },
  { value: "/tech-docs", label: "Technical Documentation" },
  { value: "/tier-management", label: "Tier Management" },
  { value: "/tier-management/new", label: "New Tier Discount" },
  { value: "/user-docs", label: "User Documentation" },
  { value: "/watchlist", label: "Watchlist" },
  { value: "/admin/scripts", label: "Admin Scripts" },
]

export const UNIFIED_TASKS: UnifiedTask[] = [
  // Foundation & Module System
  {
    id: "framework-001",
    planId: "FWK-001",
    title: "Implement Error Prevention Infrastructure",
    description: "Add comprehensive error boundaries and null safety checks throughout the application",
    type: "Framework",
    category: "Error Handling",
    epic: "Foundation",
    status: "To Do",
    priority: "Critical",
    storyPoints: 8,
    estimateDuration: "3 days",
    dueDate: "2025-10-10",
    completedDate: null,
    phase: "Phase 0",
  },
  {
    id: "framework-002",
    planId: "FWK-002",
    title: "Create Modular Settings System",
    description: "Implement feature flags and module-based configuration system for safer rollouts",
    type: "Framework",
    category: "Architecture",
    epic: "Foundation",
    status: "To Do",
    priority: "Critical",
    storyPoints: 13,
    estimateDuration: "5 days",
    dueDate: "2025-10-15",
    completedDate: null,
    phase: "Phase 0",
  },
  {
    id: "framework-003",
    planId: "FWK-003",
    title: "Fix toLowerCase() Null Safety Issues",
    description: "Add null checks to all 65+ toLowerCase() calls throughout the codebase",
    type: "Framework",
    category: "Bug Fix",
    epic: "Foundation",
    status: "To Do",
    priority: "Critical",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-10-08",
    completedDate: null,
    phase: "Phase 0",
  },
  // Atomic Design
  {
    id: "framework-004",
    planId: "FWK-004",
    title: "Create Basic UI Atoms",
    description: "Build foundational UI components: Button, Input, Card, Badge, Loading indicators",
    type: "Framework",
    category: "UI Components",
    epic: "Atomic Design",
    status: "To Do",
    priority: "High",
    storyPoints: 8,
    estimateDuration: "3 days",
    dueDate: "2025-10-18",
    completedDate: null,
    phase: "Phase 1",
  },
  {
    id: "framework-005",
    planId: "FWK-005",
    title: "Build Form Molecules",
    description: "Create reusable form components: SearchBox, FormField, ActionButtons",
    type: "Framework",
    category: "UI Components",
    epic: "Atomic Design",
    status: "To Do",
    priority: "High",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-10-20",
    completedDate: null,
    phase: "Phase 1",
  },
  {
    id: "framework-006",
    planId: "FWK-006",
    title: "Create Data Display Molecules",
    description: "Build components for data display: DataCell, MetricCard, AlertMessage",
    type: "Framework",
    category: "UI Components",
    epic: "Atomic Design",
    status: "To Do",
    priority: "Medium",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-10-22",
    completedDate: null,
    phase: "Phase 1",
  },
  // Layout & Navigation
  {
    id: "framework-007",
    planId: "FWK-007",
    title: "Build Layout Organisms",
    description: "Create AppLayout, Header, and Sidebar components with module-aware routing",
    type: "Framework",
    category: "Layout",
    epic: "Layout",
    status: "To Do",
    priority: "High",
    storyPoints: 8,
    estimateDuration: "3 days",
    dueDate: "2025-10-25",
    completedDate: null,
    phase: "Phase 2",
  },
  {
    id: "framework-008",
    planId: "FWK-008",
    title: "Implement Navigation System",
    description: "Build module-aware navigation with proper routing and breadcrumbs",
    type: "Framework",
    category: "Navigation",
    epic: "Layout",
    status: "To Do",
    priority: "High",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-10-27",
    completedDate: null,
    phase: "Phase 2",
  },
  // Authentication
  {
    id: "framework-009",
    planId: "FWK-009",
    title: "Add Auth Error Boundaries",
    description: "Implement comprehensive error handling for authentication failures",
    type: "Framework",
    category: "Authentication",
    epic: "Authentication",
    status: "To Do",
    priority: "High",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-10-30",
    completedDate: null,
    phase: "Phase 3",
  },
  {
    id: "framework-010",
    planId: "FWK-010",
    title: "Module-Aware Auth Integration",
    description: "Integrate authentication with module system for feature-based access control",
    type: "Framework",
    category: "Authentication",
    epic: "Authentication",
    status: "To Do",
    priority: "Medium",
    storyPoints: 8,
    estimateDuration: "3 days",
    dueDate: "2025-11-02",
    completedDate: null,
    phase: "Phase 3",
  },
  // Pricing Engine
  {
    id: "framework-011",
    planId: "FWK-011",
    title: "Refactor Pricing Engine - Null Safety",
    description: "Fix all toLowerCase() calls and add null checks in pricing calculations",
    type: "Framework",
    category: "Pricing",
    epic: "Pricing Engine",
    status: "To Do",
    priority: "Critical",
    storyPoints: 8,
    estimateDuration: "3 days",
    dueDate: "2025-11-05",
    completedDate: null,
    phase: "Phase 4",
  },
  {
    id: "framework-012",
    planId: "FWK-012",
    title: "Extract Pricing Business Logic",
    description: "Move pricing calculations to pure functions for better testability",
    type: "Framework",
    category: "Pricing",
    epic: "Pricing Engine",
    status: "To Do",
    priority: "High",
    storyPoints: 13,
    estimateDuration: "5 days",
    dueDate: "2025-11-10",
    completedDate: null,
    phase: "Phase 4",
  },
  {
    id: "framework-013",
    planId: "FWK-013",
    title: "Add Pricing Error Handling",
    description: "Implement comprehensive error handling for pricing calculations",
    type: "Framework",
    category: "Pricing",
    epic: "Pricing Engine",
    status: "To Do",
    priority: "High",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-11-12",
    completedDate: null,
    phase: "Phase 4",
  },
  // Discounts & Promotions
  {
    id: "framework-014",
    planId: "FWK-014",
    title: "Safe Discount Filtering",
    description: "Add null checks and safe filtering for discount operations",
    type: "Framework",
    category: "Discounts",
    epic: "Discounts",
    status: "To Do",
    priority: "High",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-11-15",
    completedDate: null,
    phase: "Phase 5",
  },
  {
    id: "framework-015",
    planId: "FWK-015",
    title: "Simplify Promotion Wizards",
    description: "Refactor promotion creation wizards for better UX and error handling",
    type: "Framework",
    category: "Promotions",
    epic: "Discounts",
    status: "To Do",
    priority: "Medium",
    storyPoints: 8,
    estimateDuration: "3 days",
    dueDate: "2025-11-18",
    completedDate: null,
    phase: "Phase 5",
  },
  {
    id: "framework-016",
    planId: "FWK-016",
    title: "Module-Based Promotion Features",
    description: "Add feature flags for promotion types and capabilities",
    type: "Framework",
    category: "Promotions",
    epic: "Discounts",
    status: "To Do",
    priority: "Medium",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-11-20",
    completedDate: null,
    phase: "Phase 5",
  },
  // Analytics
  {
    id: "framework-017",
    planId: "FWK-017",
    title: "Analytics Error Handling",
    description: "Add comprehensive error handling to analytics infrastructure",
    type: "Framework",
    category: "Analytics",
    epic: "Analytics",
    status: "To Do",
    priority: "Medium",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-11-23",
    completedDate: null,
    phase: "Phase 6",
  },
  {
    id: "framework-018",
    planId: "FWK-018",
    title: "Analytics Null Safety",
    description: "Add null checks to all analytics components and calculations",
    type: "Framework",
    category: "Analytics",
    epic: "Analytics",
    status: "To Do",
    priority: "Medium",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-11-25",
    completedDate: null,
    phase: "Phase 6",
  },
  {
    id: "framework-019",
    planId: "FWK-019",
    title: "Refactor Reporting System",
    description: "Improve reporting system with better error handling and performance",
    type: "Framework",
    category: "Analytics",
    epic: "Analytics",
    status: "To Do",
    priority: "Low",
    storyPoints: 8,
    estimateDuration: "3 days",
    dueDate: "2025-11-28",
    completedDate: null,
    phase: "Phase 6",
  },
  // Admin
  {
    id: "framework-020",
    planId: "FWK-020",
    title: "Build Module Management System",
    description: "Create admin interface for managing feature flags and modules",
    type: "Framework",
    category: "Admin",
    epic: "Admin",
    status: "To Do",
    priority: "Medium",
    storyPoints: 13,
    estimateDuration: "5 days",
    dueDate: "2025-12-03",
    completedDate: null,
    phase: "Phase 7",
  },
  {
    id: "framework-021",
    planId: "FWK-021",
    title: "Improve Audit Logging",
    description: "Enhance audit logging system with better tracking and reporting",
    type: "Framework",
    category: "Admin",
    epic: "Admin",
    status: "To Do",
    priority: "Low",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-12-05",
    completedDate: null,
    phase: "Phase 7",
  },
  {
    id: "framework-022",
    planId: "FWK-022",
    title: "Enhanced Data Management",
    description: "Improve admin data management tools with better error handling",
    type: "Framework",
    category: "Admin",
    epic: "Admin",
    status: "To Do",
    priority: "Low",
    storyPoints: 8,
    estimateDuration: "3 days",
    dueDate: "2025-12-08",
    completedDate: null,
    phase: "Phase 7",
  },
  // System Optimization
  {
    id: "framework-023",
    planId: "FWK-023",
    title: "Refine Real-Time Features",
    description: "Optimize real-time updates and notifications system",
    type: "Framework",
    category: "Real-Time",
    epic: "System Optimization",
    status: "To Do",
    priority: "Low",
    storyPoints: 8,
    estimateDuration: "3 days",
    dueDate: "2025-12-11",
    completedDate: null,
    phase: "Phase 8",
  },
  {
    id: "framework-024",
    planId: "FWK-024",
    title: "Comprehensive Testing Suite",
    description: "Build end-to-end testing suite for critical user flows",
    type: "Framework",
    category: "Testing",
    epic: "System Optimization",
    status: "To Do",
    priority: "Medium",
    storyPoints: 13,
    estimateDuration: "5 days",
    dueDate: "2025-12-16",
    completedDate: null,
    phase: "Phase 8",
  },
  {
    id: "framework-025",
    planId: "FWK-025",
    title: "Performance Optimization",
    description: "Optimize application performance and loading times",
    type: "Framework",
    category: "Performance",
    epic: "System Optimization",
    status: "To Do",
    priority: "Low",
    storyPoints: 8,
    estimateDuration: "3 days",
    dueDate: "2025-12-19",
    completedDate: null,
    phase: "Phase 8",
  },
  // Tier Management Implementation (34 tasks)
  // Database & Core APIs (15 tasks - 48 SP)
  {
    id: "tm-001",
    planId: "TM-001",
    title: "Create discount_rules table schema",
    description: "Design and implement the core discount_rules table with all required fields",
    type: "Build",
    category: "Database",
    epic: "Database & Core APIs",
    status: "Done",
    priority: "Critical",
    storyPoints: 3,
    estimateDuration: "1 day",
    dueDate: "2025-01-15",
    completedDate: "2025-01-10",
    phase: "Phase 1",
  },
  {
    id: "tm-002",
    planId: "TM-002",
    title: "Create discount_rule_tiers table schema",
    description: "Implement tier definitions table (A/B/C tiers with discount values)",
    type: "Build",
    category: "Database",
    epic: "Database & Core APIs",
    status: "Done",
    priority: "Critical",
    storyPoints: 3,
    estimateDuration: "1 day",
    dueDate: "2025-01-15",
    completedDate: "2025-01-10",
    phase: "Phase 1",
  },
  {
    id: "tm-003",
    planId: "TM-003",
    title: "Create customer_tier_assignments table",
    description: "Implement per-rule customer tier assignment table",
    type: "Build",
    category: "Database",
    epic: "Database & Core APIs",
    status: "Done",
    priority: "Critical",
    storyPoints: 3,
    estimateDuration: "1 day",
    dueDate: "2025-01-16",
    completedDate: "2025-01-11",
    phase: "Phase 1",
  },
  {
    id: "tm-004",
    planId: "TM-004",
    title: "Create tier_assignment_audit table",
    description: "Implement audit trail for tier assignment changes",
    type: "Build",
    category: "Database",
    epic: "Database & Core APIs",
    status: "Done",
    priority: "High",
    storyPoints: 2,
    estimateDuration: "0.5 days",
    dueDate: "2025-01-16",
    completedDate: "2025-01-11",
    phase: "Phase 1",
  },
  {
    id: "tm-005",
    planId: "TM-005",
    title: "Add database indexes for performance",
    description: "Create indexes on frequently queried fields for optimal performance",
    type: "Build",
    category: "Database",
    epic: "Database & Core APIs",
    status: "Done",
    priority: "High",
    storyPoints: 2,
    estimateDuration: "0.5 days",
    dueDate: "2025-01-17",
    completedDate: "2025-01-12",
    phase: "Phase 1",
  },
  {
    id: "tm-006",
    planId: "TM-006",
    title: "Create discount rules API endpoints",
    description: "Implement CRUD API routes for discount rules management",
    type: "Build",
    category: "API",
    epic: "Database & Core APIs",
    status: "Done",
    priority: "Critical",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-01-19",
    completedDate: "2025-01-14",
    phase: "Phase 1",
  },
  {
    id: "tm-007",
    planId: "TM-007",
    title: "Create tier configuration API endpoints",
    description: "Implement API routes for managing tier definitions (A/B/C)",
    type: "Build",
    category: "API",
    epic: "Database & Core APIs",
    status: "Done",
    priority: "Critical",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-01-21",
    completedDate: "2025-01-16",
    phase: "Phase 1",
  },
  {
    id: "tm-008",
    planId: "TM-008",
    title: "Create customer assignment API endpoints",
    description: "Implement API routes for assigning customers to tiers",
    type: "Build",
    category: "API",
    epic: "Database & Core APIs",
    status: "Done",
    priority: "Critical",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-01-23",
    completedDate: "2025-01-18",
    phase: "Phase 1",
  },
  {
    id: "tm-009",
    planId: "TM-009",
    title: "Implement tier assignment validation logic",
    description: "Add business rules validation for tier assignments",
    type: "Build",
    category: "Business Logic",
    epic: "Database & Core APIs",
    status: "Done",
    priority: "High",
    storyPoints: 3,
    estimateDuration: "1 day",
    dueDate: "2025-01-24",
    completedDate: "2025-01-19",
    phase: "Phase 1",
  },
  {
    id: "tm-010",
    planId: "TM-010",
    title: "Create audit logging service",
    description: "Implement service to track all tier assignment changes",
    type: "Build",
    category: "Audit",
    epic: "Database & Core APIs",
    status: "Done",
    priority: "High",
    storyPoints: 3,
    estimateDuration: "1 day",
    dueDate: "2025-01-25",
    completedDate: "2025-01-20",
    phase: "Phase 1",
  },
  {
    id: "tm-011",
    planId: "TM-011",
    title: "Add error handling for API routes",
    description: "Implement comprehensive error handling and validation",
    type: "Build",
    category: "Error Handling",
    epic: "Database & Core APIs",
    status: "Done",
    priority: "High",
    storyPoints: 3,
    estimateDuration: "1 day",
    dueDate: "2025-01-26",
    completedDate: "2025-01-21",
    phase: "Phase 1",
  },
  {
    id: "tm-012",
    planId: "TM-012",
    title: "Create data migration scripts",
    description: "Build scripts to migrate existing discount data to new schema",
    type: "Build",
    category: "Migration",
    epic: "Database & Core APIs",
    status: "Done",
    priority: "High",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-01-28",
    completedDate: "2025-01-23",
    phase: "Phase 1",
  },
  {
    id: "tm-013",
    planId: "TM-013",
    title: "Implement rule conflict detection",
    description: "Add logic to detect and prevent conflicting discount rules",
    type: "Build",
    category: "Business Logic",
    epic: "Database & Core APIs",
    status: "Done",
    priority: "Medium",
    storyPoints: 3,
    estimateDuration: "1 day",
    dueDate: "2025-01-29",
    completedDate: "2025-01-24",
    phase: "Phase 1",
  },
  {
    id: "tm-014",
    planId: "TM-014",
    title: "Add rule versioning support",
    description: "Implement version control for discount rule changes",
    type: "Build",
    category: "Versioning",
    epic: "Database & Core APIs",
    status: "Done",
    priority: "Medium",
    storyPoints: 3,
    estimateDuration: "1 day",
    dueDate: "2025-01-30",
    completedDate: "2025-01-25",
    phase: "Phase 1",
  },
  {
    id: "tm-015",
    planId: "TM-015",
    title: "Create API documentation",
    description: "Document all tier management API endpoints with examples",
    type: "Documentation",
    category: "API Docs",
    epic: "Database & Core APIs",
    status: "Done",
    priority: "Medium",
    storyPoints: 2,
    estimateDuration: "0.5 days",
    dueDate: "2025-01-31",
    completedDate: "2025-01-26",
    phase: "Phase 1",
  },

  // Wizard UI Enhancement (6 tasks - 39 SP)
  {
    id: "tm-016",
    planId: "TM-016",
    title: "Add tier configuration step to wizard",
    description: "Extend discount wizard with tier definition interface (A/B/C)",
    type: "Build",
    category: "UI",
    epic: "Wizard UI Enhancement",
    status: "Done",
    priority: "Critical",
    storyPoints: 8,
    estimateDuration: "3 days",
    dueDate: "2025-02-03",
    completedDate: "2025-01-29",
    phase: "Phase 2",
  },
  {
    id: "tm-017",
    planId: "TM-017",
    title: "Build tier discount value input UI",
    description: "Create interface for setting discount values per tier",
    type: "Build",
    category: "UI",
    epic: "Wizard UI Enhancement",
    status: "Done",
    priority: "Critical",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-02-05",
    completedDate: "2025-01-31",
    phase: "Phase 2",
  },
  {
    id: "tm-018",
    planId: "TM-018",
    title: "Create customer tier assignment interface",
    description: "Build UI for assigning customers to tiers within a rule",
    type: "Build",
    category: "UI",
    epic: "Wizard UI Enhancement",
    status: "Done",
    priority: "Critical",
    storyPoints: 8,
    estimateDuration: "3 days",
    dueDate: "2025-02-08",
    completedDate: "2025-02-03",
    phase: "Phase 2",
  },
  {
    id: "tm-019",
    planId: "TM-019",
    title: "Add bulk customer assignment tool",
    description: "Implement CSV upload for bulk tier assignments",
    type: "Build",
    category: "UI",
    epic: "Wizard UI Enhancement",
    status: "Done",
    priority: "High",
    storyPoints: 8,
    estimateDuration: "3 days",
    dueDate: "2025-02-11",
    completedDate: "2025-02-06",
    phase: "Phase 2",
  },
  {
    id: "tm-020",
    planId: "TM-020",
    title: "Create tier assignment preview",
    description: "Build preview showing which customers get which discounts",
    type: "Build",
    category: "UI",
    epic: "Wizard UI Enhancement",
    status: "Done",
    priority: "High",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-02-13",
    completedDate: "2025-02-08",
    phase: "Phase 2",
  },
  {
    id: "tm-021",
    planId: "TM-021",
    title: "Add wizard validation and error messages",
    description: "Implement comprehensive validation for tier configuration",
    type: "Build",
    category: "Validation",
    epic: "Wizard UI Enhancement",
    status: "Done",
    priority: "High",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-02-15",
    completedDate: "2025-02-10",
    phase: "Phase 2",
  },

  // Pricing Engine Integration (7 tasks - 34 SP)
  {
    id: "tm-022",
    planId: "TM-022",
    title: "Integrate tier lookup in pricing engine",
    description: "Add customer tier resolution to pricing calculation flow",
    type: "Build",
    category: "Pricing Engine",
    epic: "Pricing Engine Integration",
    status: "To Do",
    priority: "Critical",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-02-18",
    completedDate: null,
    phase: "Phase 3",
  },
  {
    id: "tm-023",
    planId: "TM-023",
    title: "Implement tier-based discount calculation",
    description: "Add logic to apply correct discount based on customer tier",
    type: "Build",
    category: "Pricing Engine",
    epic: "Pricing Engine Integration",
    status: "To Do",
    priority: "Critical",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-02-20",
    completedDate: null,
    phase: "Phase 3",
  },
  {
    id: "tm-024",
    planId: "TM-024",
    title: "Add tier precedence rules",
    description: "Implement logic for handling multiple tier assignments",
    type: "Build",
    category: "Business Logic",
    epic: "Pricing Engine Integration",
    status: "To Do",
    priority: "High",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-02-22",
    completedDate: null,
    phase: "Phase 3",
  },
  {
    id: "tm-025",
    planId: "TM-025",
    title: "Implement tier caching for performance",
    description: "Add Redis caching for tier assignments to optimize lookups",
    type: "Build",
    category: "Performance",
    epic: "Pricing Engine Integration",
    status: "To Do",
    priority: "High",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-02-25",
    completedDate: null,
    phase: "Phase 3",
  },
  {
    id: "tm-026",
    planId: "TM-026",
    title: "Add tier information to pricing response",
    description: "Include tier details in pricing API responses for transparency",
    type: "Build",
    category: "API",
    epic: "Pricing Engine Integration",
    status: "To Do",
    priority: "Medium",
    storyPoints: 3,
    estimateDuration: "1 day",
    dueDate: "2025-02-26",
    completedDate: null,
    phase: "Phase 3",
  },
  {
    id: "tm-027",
    planId: "TM-027",
    title: "Implement tier-based best deal logic",
    description: "Extend no-stacking logic to consider tier-based discounts",
    type: "Build",
    category: "Business Logic",
    epic: "Pricing Engine Integration",
    status: "To Do",
    priority: "High",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-02-28",
    completedDate: null,
    phase: "Phase 3",
  },
  {
    id: "tm-028",
    planId: "TM-028",
    title: "Add tier discount audit logging",
    description: "Log all tier-based discount applications for compliance",
    type: "Build",
    category: "Audit",
    epic: "Pricing Engine Integration",
    status: "To Do",
    priority: "High",
    storyPoints: 3,
    estimateDuration: "1 day",
    dueDate: "2025-03-01",
    completedDate: null,
    phase: "Phase 3",
  },

  // Testing & Management Tools (6 tasks - 42 SP)
  {
    id: "tm-029",
    planId: "TM-029",
    title: "Build customer tier dashboard",
    description: "Create management interface showing all tier assignments",
    type: "Build",
    category: "UI",
    epic: "Testing & Management",
    status: "To Do",
    priority: "High",
    storyPoints: 8,
    estimateDuration: "3 days",
    dueDate: "2025-03-04",
    completedDate: null,
    phase: "Phase 4",
  },
  {
    id: "tm-030",
    planId: "TM-030",
    title: "Create bulk tier assignment tool",
    description: "Build interface for managing tier assignments at scale",
    type: "Build",
    category: "UI",
    epic: "Testing & Management",
    status: "To Do",
    priority: "Medium",
    storyPoints: 8,
    estimateDuration: "3 days",
    dueDate: "2025-03-07",
    completedDate: null,
    phase: "Phase 4",
  },
  {
    id: "tm-031",
    planId: "TM-031",
    title: "Add tier testing to simulator",
    description: "Extend pricing simulator to test tier-based scenarios",
    type: "Build",
    category: "Testing",
    epic: "Testing & Management",
    status: "To Do",
    priority: "High",
    storyPoints: 8,
    estimateDuration: "3 days",
    dueDate: "2025-03-10",
    completedDate: null,
    phase: "Phase 4",
  },
  {
    id: "tm-032",
    planId: "TM-032",
    title: "Create tier management test suite",
    description: "Build comprehensive unit and integration tests",
    type: "Testing",
    category: "Testing",
    epic: "Testing & Management",
    status: "Done",
    priority: "High",
    storyPoints: 8,
    estimateDuration: "3 days",
    dueDate: "2025-03-13",
    completedDate: "2025-03-11",
    phase: "Phase 4",
  },
  {
    id: "tm-033",
    planId: "TM-033",
    title: "Write user documentation",
    description: "Create end-user guides for tier management features",
    type: "Documentation",
    category: "User Docs",
    epic: "Testing & Management",
    status: "Done",
    priority: "Medium",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-03-15",
    completedDate: "2025-03-13",
    phase: "Phase 4",
  },
  {
    id: "tm-034",
    planId: "TM-034",
    title: "Write technical documentation",
    description: "Document tier management architecture and APIs",
    type: "Documentation",
    category: "Tech Docs",
    epic: "Testing & Management",
    status: "Done",
    priority: "Medium",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-03-17",
    completedDate: "2025-03-15",
    phase: "Phase 4",
  },

  // Deduplication Epic (7 tasks - 47 SP)
  {
    id: "dedupe-001",
    planId: "DDP-001",
    title: "Consolidate Wizard Components",
    description:
      "Merge create/edit modal pairs into single components with mode prop for Customer Discounts, Inventory Discounts, BOGO Promotions, Bundle Deals, Volume Pricing, and Tiered Pricing wizards. Standardize step patterns while preserving unique business logic.",
    type: "Build",
    category: "UI Components",
    epic: "Dedupe Features",
    status: "To Do",
    priority: "High",
    storyPoints: 8,
    estimateDuration: "3 days",
    dueDate: "2025-04-15",
    completedDate: null,
    phase: "Consolidate Wizard Components",
  },
  {
    id: "dedupe-002",
    planId: "DDP-002",
    title: "Merge Pricing Rules Database Tables",
    description:
      "Consolidate volume_pricing_rules and tiered_pricing_rules into discount_rules table. Migrate all tiers to discount_rule_tiers. Create migration scripts and update all code references. Preserve pricing_applications audit trail.",
    type: "Build",
    category: "Database",
    epic: "Dedupe Features",
    status: "To Do",
    priority: "Critical",
    storyPoints: 13,
    estimateDuration: "5 days",
    dueDate: "2025-04-22",
    completedDate: null,
    phase: "Merge Pricing Rules Database Tables",
  },
  {
    id: "dedupe-003",
    planId: "DDP-003",
    title: "Unify Validation APIs",
    description:
      "Create unified /api/validation/discounts endpoint to replace separate /api/discounts/validate and /api/promotions/validate endpoints. Support all discount types via request body. Maintain backward compatibility during transition.",
    type: "Build",
    category: "API",
    epic: "Dedupe Features",
    status: "To Do",
    priority: "High",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-04-25",
    completedDate: null,
    phase: "Unify Validation APIs",
  },
  {
    id: "dedupe-004",
    planId: "DDP-004",
    title: "Restructure Pricing APIs",
    description:
      "Move /api/pricing-rules/* endpoints to /api/pricing/rules/* hierarchy for consistent organization. Add redirects for backward compatibility. Update all client code and documentation.",
    type: "Build",
    category: "API",
    epic: "Dedupe Features",
    status: "To Do",
    priority: "High",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-04-28",
    completedDate: null,
    phase: "Restructure Pricing APIs",
  },
  {
    id: "dedupe-005",
    planId: "DDP-005",
    title: "Consolidate Analytics Endpoints",
    description:
      "Merge /api/analytics/realtime and /api/analytics/realtime-events into single endpoint with query parameters. Standardize response formats across all analytics endpoints. Preserve all predictive analytics capabilities.",
    type: "Build",
    category: "API",
    epic: "Dedupe Features",
    status: "To Do",
    priority: "Medium",
    storyPoints: 8,
    estimateDuration: "3 days",
    dueDate: "2025-05-02",
    completedDate: null,
    phase: "Consolidate Analytics Endpoints",
  },
  {
    id: "dedupe-006",
    planId: "DDP-006",
    title: "Simplify Dashboard Components",
    description:
      "Consolidate real-time dashboard components into tabbed interface. Merge overlapping metric displays while preserving domain-specific dashboards for Promotions, Tiers, and Pricing. Update Settings page to reflect changes.",
    type: "Build",
    category: "UI Components",
    epic: "Dedupe Features",
    status: "To Do",
    priority: "Medium",
    storyPoints: 5,
    estimateDuration: "2 days",
    dueDate: "2025-05-05",
    completedDate: null,
    phase: "Simplify Dashboard Components",
  },
  {
    id: "dedupe-007",
    planId: "DDP-007",
    title: "Merge Simulator Features",
    description:
      "Combine /simulator and scenario testing into unified interface with tabs. Add scenario comparison as built-in feature. Preserve all advanced simulation and modeling capabilities.",
    type: "Build",
    category: "UI Components",
    epic: "Dedupe Features",
    status: "To Do",
    priority: "Medium",
    storyPoints: 3,
    estimateDuration: "1 day",
    dueDate: "2025-05-07",
    completedDate: null,
    phase: "Merge Simulator Features",
  },
]
