-- Seed Tier Management Tasks (34 tasks from Phase 1-4)

INSERT INTO user_stories (id, title, description, status, priority, story_points, tasks, dependencies, labels, epic, acceptance_criteria)
VALUES
-- Phase 1: Database & Core APIs (15 tasks)
('tm-001', 'Create discount_rules table schema', 'Design and implement the core discount_rules table with all required fields', 'Done', 'Critical', 3, '[]', '[]', '["Build", "Database"]', 'Phase 1: Database & Core APIs', '["Table schema created", "Migrations run", "Indexes added"]'),
('tm-002', 'Create discount_rule_tiers table schema', 'Implement tier definitions table (A/B/C tiers with discount values)', 'Done', 'Critical', 3, '[]', '[]', '["Build", "Database"]', 'Phase 1: Database & Core APIs', '["Tier table created", "Foreign keys configured", "Data validated"]'),
('tm-003', 'Create customer_tier_assignments table', 'Implement per-rule customer tier assignment table', 'Done', 'Critical', 3, '[]', '[]', '["Build", "Database"]', 'Phase 1: Database & Core APIs', '["Assignment table created", "Relationships defined", "Constraints added"]'),
('tm-004', 'Create tier_assignment_audit table', 'Implement audit trail for tier assignment changes', 'Done', 'High', 2, '[]', '[]', '["Build", "Database"]', 'Phase 1: Database & Core APIs', '["Audit table created", "Triggers configured", "Logging working"]'),
('tm-005', 'Add database indexes for performance', 'Create indexes on frequently queried fields for optimal performance', 'Done', 'High', 2, '[]', '[]', '["Build", "Database"]', 'Phase 1: Database & Core APIs', '["Indexes created", "Query performance improved", "Execution plans verified"]'),
('tm-006', 'Create discount rules API endpoints', 'Implement CRUD API routes for discount rules management', 'Done', 'Critical', 5, '[]', '[]', '["Build", "API"]', 'Phase 1: Database & Core APIs', '["CRUD endpoints created", "Validation added", "Tests passing"]'),
('tm-007', 'Create tier configuration API endpoints', 'Implement API routes for managing tier definitions (A/B/C)', 'Done', 'Critical', 5, '[]', '[]', '["Build", "API"]', 'Phase 1: Database & Core APIs', '["Tier APIs created", "Documentation written", "Error handling added"]'),
('tm-008', 'Create customer assignment API endpoints', 'Implement API routes for assigning customers to tiers', 'Done', 'Critical', 5, '[]', '[]', '["Build", "API"]', 'Phase 1: Database & Core APIs', '["Assignment APIs created", "Bulk operations supported", "Validation working"]'),
('tm-009', 'Implement tier assignment validation logic', 'Add business rules validation for tier assignments', 'Done', 'High', 3, '[]', '[]', '["Build", "Business Logic"]', 'Phase 1: Database & Core APIs', '["Validation rules implemented", "Edge cases handled", "Tests added"]'),
('tm-010', 'Create audit logging service', 'Implement service to track all tier assignment changes', 'Done', 'High', 3, '[]', '[]', '["Build", "Audit"]', 'Phase 1: Database & Core APIs', '["Audit service created", "All changes logged", "Reporting available"]'),
('tm-011', 'Add error handling for API routes', 'Implement comprehensive error handling and validation', 'Done', 'High', 3, '[]', '[]', '["Build", "Error Handling"]', 'Phase 1: Database & Core APIs', '["Error handling added", "User-friendly messages", "Logging configured"]'),
('tm-012', 'Create data migration scripts', 'Build scripts to migrate existing discount data to new schema', 'Done', 'High', 5, '[]', '[]', '["Build", "Migration"]', 'Phase 1: Database & Core APIs', '["Migration scripts created", "Data migrated successfully", "Rollback tested"]'),
('tm-013', 'Implement rule conflict detection', 'Add logic to detect and prevent conflicting discount rules', 'Done', 'Medium', 3, '[]', '[]', '["Build", "Business Logic"]', 'Phase 1: Database & Core APIs', '["Conflict detection working", "Warnings displayed", "Prevention logic added"]'),
('tm-014', 'Add rule versioning support', 'Implement version control for discount rule changes', 'Done', 'Medium', 3, '[]', '[]', '["Build", "Versioning"]', 'Phase 1: Database & Core APIs', '["Versioning implemented", "History tracked", "Rollback supported"]'),
('tm-015', 'Create API documentation', 'Document all tier management API endpoints with examples', 'Done', 'Medium', 2, '[]', '[]', '["Documentation", "API Docs"]', 'Phase 1: Database & Core APIs', '["API docs written", "Examples provided", "Postman collection created"]'),

-- Phase 2: Wizard UI Enhancement (6 tasks)
('tm-016', 'Add tier configuration step to wizard', 'Extend discount wizard with tier definition interface (A/B/C)', 'Done', 'Critical', 8, '[]', '[]', '["Build", "UI"]', 'Phase 2: Wizard UI Enhancement', '["Wizard step added", "UI responsive", "Validation working"]'),
('tm-017', 'Build tier discount value input UI', 'Create interface for setting discount values per tier', 'Done', 'Critical', 5, '[]', '[]', '["Build", "UI"]', 'Phase 2: Wizard UI Enhancement', '["Input UI created", "Validation added", "UX tested"]'),
('tm-018', 'Create customer tier assignment interface', 'Build UI for assigning customers to tiers within a rule', 'Done', 'Critical', 8, '[]', '[]', '["Build", "UI"]', 'Phase 2: Wizard UI Enhancement', '["Assignment UI built", "Search working", "Bulk actions supported"]'),
('tm-019', 'Add bulk customer assignment tool', 'Implement CSV upload for bulk tier assignments', 'Done', 'High', 8, '[]', '[]', '["Build", "UI"]', 'Phase 2: Wizard UI Enhancement', '["CSV upload working", "Validation added", "Error reporting clear"]'),
('tm-020', 'Create tier assignment preview', 'Build preview showing which customers get which discounts', 'Done', 'High', 5, '[]', '[]', '["Build", "UI"]', 'Phase 2: Wizard UI Enhancement', '["Preview UI built", "Data accurate", "Performance optimized"]'),
('tm-021', 'Add wizard validation and error messages', 'Implement comprehensive validation for tier configuration', 'Done', 'High', 5, '[]', '[]', '["Build", "Validation"]', 'Phase 2: Wizard UI Enhancement', '["Validation complete", "Error messages clear", "User guidance provided"]'),

-- Phase 3: Pricing Engine Integration (7 tasks)
('tm-022', 'Integrate tier lookup in pricing engine', 'Add customer tier resolution to pricing calculation flow', 'To Do', 'Critical', 5, '[]', '[]', '["Build", "Pricing Engine"]', 'Phase 3: Pricing Engine Integration', '["Tier lookup integrated", "Performance acceptable", "Caching implemented"]'),
('tm-023', 'Implement tier-based discount calculation', 'Add logic to apply correct discount based on customer tier', 'To Do', 'Critical', 5, '[]', '[]', '["Build", "Pricing Engine"]', 'Phase 3: Pricing Engine Integration', '["Calculation logic added", "Tests passing", "Edge cases handled"]'),
('tm-024', 'Add tier precedence rules', 'Implement logic for handling multiple tier assignments', 'To Do', 'High', 5, '[]', '[]', '["Build", "Business Logic"]', 'Phase 3: Pricing Engine Integration', '["Precedence rules defined", "Logic implemented", "Documentation written"]'),
('tm-025', 'Implement tier caching for performance', 'Add Redis caching for tier assignments to optimize lookups', 'To Do', 'High', 5, '[]', '[]', '["Build", "Performance"]', 'Phase 3: Pricing Engine Integration', '["Caching implemented", "Performance improved", "Cache invalidation working"]'),
('tm-026', 'Add tier information to pricing response', 'Include tier details in pricing API responses for transparency', 'To Do', 'Medium', 3, '[]', '[]', '["Build", "API"]', 'Phase 3: Pricing Engine Integration', '["Tier info in response", "Documentation updated", "Backward compatible"]'),
('tm-027', 'Implement tier-based best deal logic', 'Extend no-stacking logic to consider tier-based discounts', 'To Do', 'High', 5, '[]', '[]', '["Build", "Business Logic"]', 'Phase 3: Pricing Engine Integration', '["Best deal logic updated", "Tier discounts considered", "Tests comprehensive"]'),
('tm-028', 'Add tier discount audit logging', 'Log all tier-based discount applications for compliance', 'To Do', 'High', 3, '[]', '[]', '["Build", "Audit"]', 'Phase 3: Pricing Engine Integration', '["Audit logging added", "Compliance verified", "Reporting available"]'),

-- Phase 4: Testing & Management Tools (6 tasks)
('tm-029', 'Build customer tier dashboard', 'Create management interface showing all tier assignments', 'To Do', 'High', 8, '[]', '[]', '["Build", "UI"]', 'Phase 4: Testing & Management', '["Dashboard built", "Data accurate", "Filters working"]'),
('tm-030', 'Create bulk tier assignment tool', 'Build interface for managing tier assignments at scale', 'To Do', 'Medium', 8, '[]', '[]', '["Build", "UI"]', 'Phase 4: Testing & Management', '["Bulk tool created", "Performance acceptable", "Error handling robust"]'),
('tm-031', 'Add tier testing to simulator', 'Extend pricing simulator to test tier-based scenarios', 'To Do', 'High', 8, '[]', '[]', '["Build", "Testing"]', 'Phase 4: Testing & Management', '["Simulator extended", "Tier scenarios testable", "Results accurate"]'),
('tm-032', 'Create tier management test suite', 'Build comprehensive unit and integration tests', 'Done', 'High', 8, '[]', '[]', '["Testing", "Testing"]', 'Phase 4: Testing & Management', '["Test suite created", "Coverage >80%", "CI/CD integrated"]'),
('tm-033', 'Write user documentation', 'Create end-user guides for tier management features', 'Done', 'Medium', 5, '[]', '[]', '["Documentation", "User Docs"]', 'Phase 4: Testing & Management', '["User docs written", "Screenshots added", "Examples provided"]'),
('tm-034', 'Write technical documentation', 'Document tier management architecture and APIs', 'Done', 'Medium', 5, '[]', '[]', '["Documentation", "Tech Docs"]', 'Phase 4: Testing & Management', '["Tech docs written", "Architecture diagrams added", "API reference complete"]');
