-- Script 122: Add Product Detail Page with Performance Insights Story
-- Creates user story for the comprehensive product analytics page

BEGIN;

-- Insert Product Detail Page with Performance Insights story
-- ID will be auto-generated by BIGSERIAL
INSERT INTO user_stories (
  story_id, title, description, status, priority, story_points,
  acceptance_criteria, technical_notes, epic, labels,
  created_by, updated_by, created_at, updated_at
)
VALUES (
  'PROD-009',
  'Product Detail Page with Performance Insights',
  'As a business analyst, I want to view comprehensive product performance data including sales trends, promotion effectiveness, and top customers so that I can make data-driven decisions about product strategy and pricing.',
  'Done',
  'High',
  13,
  '### Scenario 1: View Product Overview
```gherkin
Given I am logged into the system
When I navigate to /products/[product-id]
Then I see the product detail page
And I see product information: name, SKU, category, brand, price, cost
And I see key metrics: total revenue, units sold, profit margin, avg discount
And I see performance indicators with trend arrows
And I see a revenue trend chart
And I see a sales volume chart
