-- Add Task ID Generation User Stories to epic-refactor
-- These stories implement automatic task ID generation based on EPIC names

-- Task 7: Task ID Generation from EPIC
INSERT INTO user_stories (
  id,
  title,
  description,
  user_type,
  goal,
  reason,
  story_type,
  parent_id,
  epic,
  priority,
  status,
  story_points,
  assignee,
  reporter,
  acceptance_criteria,
  created_at
) VALUES (
  'refactor-007',
  'Task ID Generation from EPIC',
  'As a project manager, I want task IDs to be automatically generated based on the EPIC name, so that tasks are clearly associated with their parent EPIC and maintain a consistent naming convention.',
  'project manager',
  'task IDs to be automatically generated based on the EPIC name',
  'tasks are clearly associated with their parent EPIC and maintain a consistent naming convention',
  'task',
  'epic-refactor',
  'epic-refactor',
  'high',
  'todo',
  8,
  'Antonio Jones',
  'Antonio Jones',
  '- Given an EPIC exists with the name "Project Alpha" and the EPIC code is configured as "PROJ", when I create a new task under this EPIC, then the task ID should be generated as "PROJ-0001" and the task ID format should follow the pattern "AAAA-XXXX"
- Given an EPIC exists with the name "BETA", when I create a new task under this EPIC, then the task ID should be generated as "BETA-0001"
- Given an EPIC exists with the name "Infrastructure" and the EPIC code is extracted as "INFR", when I create a new task under this EPIC, then the task ID should be generated as "INFR-0001"
- Given an EPIC exists with the name "API" and the EPIC code is padded to "API-" or configured as "APIX", when I create a new task under this EPIC, then the task ID should be generated following the 4-character requirement and the task ID should follow the pattern "AAAA-0001"
- Given I am creating a new task under EPIC "PROJ", when the task form is displayed, then the Task ID field should be autogenerated as "PROJ-####" and the Task ID field should be read-only and I should not be able to manually edit the Task ID
- Given a parent task exists with ID "PROJ-0001", when I create a subtask under this task, then the subtask ID should be generated as "PROJ-0001-01" and the subtask should inherit the EPIC code from the parent task
- Given an EPIC exists with the name "development" and the EPIC code is derived as "DEVE", when I create a new task under this EPIC, then the task ID should be generated as "DEVE-0001" in uppercase and the EPIC code should always be displayed in uppercase
- Given any EPIC with code "AAAA", when a task is created, then the task ID must contain a dash separator between the EPIC code and number and the format must be "AAAA-XXXX" where the dash is always present
- Given a task exists with ID "PROJ-0025", when I view the task details, then the Task ID "PROJ-0025" should be clearly displayed and I should be able to identify that it belongs to EPIC "PROJ" and the task number within the EPIC is "0025"',
  NOW()
);

-- Task 8: Sequential Task Numbering
INSERT INTO user_stories (
  id,
  title,
  description,
  user_type,
  goal,
  reason,
  story_type,
  parent_id,
  epic,
  priority,
  status,
  story_points,
  assignee,
  reporter,
  acceptance_criteria,
  created_at
) VALUES (
  'refactor-008',
  'Sequential Task Numbering',
  'As a user creating multiple tasks, I want task numbers to increment sequentially within each EPIC, so that each task has a unique identifier that shows the order of creation.',
  'user creating multiple tasks',
  'task numbers to increment sequentially within each EPIC',
  'each task has a unique identifier that shows the order of creation',
  'task',
  'epic-refactor',
  'epic-refactor',
  'high',
  'todo',
  5,
  'Antonio Jones',
  'Antonio Jones',
  '- Given an EPIC exists with code "PROJ" and a task already exists with ID "PROJ-0001", when I create a new task under the same EPIC, then the task ID should be generated as "PROJ-0002" and when I create another task, then the task ID should be generated as "PROJ-0003"
- Given EPIC "Project Alpha" with code "PROJ" has tasks "PROJ-0001" and "PROJ-0002" and EPIC "Beta Release" with code "BETA" exists, when I create a new task under EPIC "Beta Release", then the task ID should be generated as "BETA-0001" and it should not continue the numbering from EPIC "Project Alpha"
- Given an EPIC with code "PROJ", when I create the first task, then the task ID should be "PROJ-0001" with leading zeros and when I create the 10th task, then the task ID should be "PROJ-0010" and when I create the 100th task, then the task ID should be "PROJ-0100" and when I create the 1000th task, then the task ID should be "PROJ-1000"',
  NOW()
);

-- Log task creation
INSERT INTO task_events (
  task_id,
  event_type,
  triggered_by,
  metadata
) VALUES (
  'refactor-007',
  'task_created',
  'v0-agent',
  jsonb_build_object(
    'creation_note', 'Added Task ID Generation from EPIC story with Gherkin acceptance criteria',
    'story_points', 8,
    'priority', 'high'
  )
),
(
  'refactor-008',
  'task_created',
  'v0-agent',
  jsonb_build_object(
    'creation_note', 'Added Sequential Task Numbering story with Gherkin acceptance criteria',
    'story_points', 5,
    'priority', 'high'
  )
);
